### PR TITLE
feat: setup CDN support

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Was slightly harder to parse since it's not following our standard format (which leads with the registerLanguage call - which doesn't need to be in a closure of it's own)... Looks fine (at a glance - I only looked at the `dist` and wrapper), but why reinvent the wheel?

Would you still run it inside the main test suite periodically for the security checks the core library provides?

**Comment by NullVoxPopuli** [comment]
>  I only looked at the dist and wrapper), but why reinvent the wheel?

Because this was easy and self-contained. I find having to interact with a separate repo just to build quite unergonomic. 

> [grumble]Minimizers should not use the letter O when it's so close to 0.[/grumble] LOL

it is a weird choice! but 🤷 no one is supposed to look at it 🙃 

> Would you still run it inside the main test suite periodically for the security checks the core library provides?

I should probably add this to my C.I. anyway

**Comment by NullVoxPopuli** [comment]
it looks like the highlightjs tests juts run detect and markup tests?
So then I don't need this at all?
image

The tests in this repo were much easier to setup: https://github.com/NullVoxPopuli/highlightjs-glimmer/blob/main/tests/index.test.js

I'm gonna message you on discord about issues I'm having with running the hljs tests in general though

**Comment by NullVoxPopuli** [comment]
Gonna merge this for now -- any other changes can happen in followup PRs

**Pull request merged**
