### PR TITLE
Refactor gjs grammar into self-contained definition

### PR DESCRIPTION
**Pull request by davidtaylorhq**
Previously, this package enabled glimmer-js support by patching into the official highlightjs javascript grammar. This is problematic if you want to support both gjs and js(/jsx) syntax highlighting alongside each other.

This commit refactors things so that glimmer-javascript is defined and exported as a standalone grammar. Instead of patching the standard javascript grammar, it uses the `subLanguage` feature to extend it cleanly. hbs-literal and template-tag support are added via additional 'contains' rules.

To maintain the existing 'override javascript grammar' behavior for existing consumers of this package, the setup APIs will register  `javascript`, `js`, `mjs` and `cjs` as aliases of the new `glimmer-javascript` grammar. Consumers who want to take advantage of the standalone grammar can import it and register using the standard `hljs.registerLanguage` technique.

In future, it may be beneficial to deprecate the custom setup functions and recommend use of the standard `registerLanguage` technique. But for now, this commit leaves all existing public API unchanged.

### CODE REVIEW

**Review by NullVoxPopuli — APPROVED** [review]
> In future, it may be beneficial to deprecate the custom setup functions and recommend use of the standard registerLanguage technique. But for now, this commit leaves all existing public API unchanged.

Agreed, thank you!

**Comment by davidtaylorhq** [comment]
Looks like I have some test issues to resolve - will take a look in the next few days 👀

**Comment by davidtaylorhq** [comment]
@NullVoxPopuli test suite is now green on this.

I noticed that this repo has build artefacts (`/dist/*` and `/highlightjs-glimmer/dist/*`) committed to the source tree. To make review easier, I haven't pushed them here. Let me know if/when I should.

**Comment by NullVoxPopuli** [comment]
> I haven't pushed them here.

sounds good, I usually do this during release!

**Pull request merged**
